# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_binary_packages:
- dplyr
- ggplot2
- testthat
- grDevices
- knitr
- rmarkdown
